### PR TITLE
Event view

### PR DESCRIPTION
**Pull request by guilherme-gjv**
# Related Issue
- #48 

### (Segundo a minha régua, tá reto dessa vez)

# Screenshots
ss

### CODE REVIEW

**Comment by guilherme-gjv** [comment]
## - You helped me in the migration part 
## - Card alterations:
- Rounded picture
- Font-bold added, but normal font to value texts
- Font-size reduced
- Background image switched to normal images, that change according to the board system photoURL

card-novo

**Comment by guilherme-gjv** [comment]
## 'Descrição' centralized

dnd

## 'Localização' switched with 'Máximo de Mesas'
- Why?
    - 'Localização' has a more variable size than 'Máximo de Mesas' and 'Data', so is better to put it separated, and not in the center as it was before

jojvento

**Comment by guilherme-gjv** [comment]
yee

finpr

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Add `dice` icon in "Mesas do evento" label and increase mx in boards container in desktop version

**Comment by guilherme-gjv** [comment]
cvs

**Review by Manuel-Antunes — APPROVED** [review]

**Pull request merged**
