### PR TITLE
Event view

### PR DESCRIPTION
**Pull request by guilherme-gjv**
# Related Issue
- #39 

# Proposed Changes
- Responsive and cool view

# Screenshots

## After

>Captura da Web_3-1-2022_113421_localhost

>Capturar

## Mobile (when there's no tables)

>mobaio0

### CODE REVIEW

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Improve pc version:

* increase top margin in main section
* decrease top margin in boards section
* fix word breaking in words

**Comment by guilherme-gjv** [comment]
Improve pc version:

- [ ] increase top margin in main section
- [ ] decrease top margin in boards section
- [ ] fix word breaking in words

Capturar

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Transform event card into a component and normalize all event card sizes

**Review by Manuel-Antunes — APPROVED** [review]
Nice!

**Pull request merged**
