### PR TITLE
Update boards component

### LINKED ISSUE #70: Update Design: componentes de mesa
Update it to the new design using tailwindCSS

Capturar  Capturar2

### PR DESCRIPTION
**Pull request by guilherme-gjv**
# Related Issue
- #70 

### ⚠️ This PR will merge it into "update-design-board-view" branch, not the "main"

# Proposed Changes

- This card will be used to show highlight boards. The boards that the user is master, etc
bcv0

- This horizontal card will be used to list all the boards the user is in.
bch0

### CODE REVIEW

**Comment by guilherme-gjv** [comment]
pera tem um erro

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Isn't equals to Stanislav style

**Review by leticiabsduarte — CHANGES_REQUESTED** [review]
We already have the new design, so always make it exactly like what Stanislav did

**Comment by Manuel-Antunes** [comment]
Please, add all screenshots

**Pull request closed without merging**
