### PR TITLE
Calendar

### LINKED ISSUE #75: Calendar
## Implement the new calendar design, based in the Figma model

- [ ] Study and understand how old design works
- [ ] Apply new design

## Old Design | New Design
calendarcurrent calendarfigma

### PR DESCRIPTION
**Pull request by guilherme-gjv**
# Related Issue
- #75 

# Proposed Changes
- Calendar stylized to new design

# Additional Info
- navbar, footer, and font family are not updated on the screenshot, because it's waiting for merge with main. But they're independent parts.
- please ignore all commits from 27th january, unless the last one.

# Checklist
- [ ] Tests
- [ ] Translations
- [ ] Documentation

# Screenshots

calendarcurrent calendarnew

### CODE REVIEW

**Review by leticiabsduarte — CHANGES_REQUESTED** [review]
- After creating an event in another month, the page loads in the current month. Change it to stay in the month you recently edited.

- Intensify the colors that identify the events, it is difficult to recognize them on mobile.

- There is a problem when you create some events on the same day on mobile version. You can try adjusting the dimensions, but if it doesn't work, a good option would be to create a tab where you can create events and visualize the existing ones when you click on the day.
Capturar

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Make the calendar day node height as before

**Comment by guilherme-gjv** [comment]
calendarcurrentcurrent

**Comment by guilherme-gjv** [comment]
- ### Our current month is February; 
- ### I created a new event in April;
    - #### BEFORE the changes, when I submit, It would be back to the current month
    - #### I fixed It, now I get backs to the same month of the new event

GIF-220204_215955

**Comment by leticiabsduarte** [comment]
@guilherme-gjv 
Great! But this error keeps here, do you want anyone help?
calendar error

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Hidden events in overflow

**Review by leticiabsduarte — CHANGES_REQUESTED** [review]
I like to repprove

**Comment by guilherme-gjv** [comment]
cellday

- this is scrollable now :D

**Pull request closed without merging**
