### PR TITLE
Add user promote button

### PR DESCRIPTION
**Pull request by duardoqueiroz**
# Related Issue
- #62 

# Proposed Changes
- add migration that sets null usernames
- add promote button

# Screenshots

> ## Updated
image
###
image

### CODE REVIEW

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Change branch base to allow

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
Please, make the promote button smaller in smartphones

**Comment by duardoqueiroz** [comment]
> Please, make the promote button smaller in smartphones

image
#
image

**Review by leticiabsduarte — APPROVED** [review]
it's working perfectly, good work!

**Pull request closed without merging**
